name: Godot CI

# run when code is pushed or PR is created
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest # use linux runner
    container:
      image: barichello/godot-ci:4.5.2 # Docker image with Godot pre-installed for CI

    steps:
      # download repo into runner
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Check Godot version
      - name: Check Godot version
        run: godot --version
        
      # run and check the project in headless mode
      - name: Import project in headless mode
        run: cd game && godot --headless --editor --quit
      
      # run all GUT tests in headless mode to verify game logic
      - name: Run GUT tests
        run: cd game && godot --headless -s addons/gut/gut_cmdln.gd -gdir=res://tests
